apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: rate-limiter
  namespace: rate-limiter
  labels:
    app: rate-limiter
spec:
  selector:
    matchLabels:
      app: rate-limiter
  endpoints:
  - port: metrics
    interval: 15s
    path: /metrics
